# Generated by Django 5.2 on 2025-05-12 20:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgerianCardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('visa', 'VISA'), ('mastercard', 'MasterCard'), ('cib', 'CIB'), ('badr', 'Banque Al Baraka')], max_length=20)),
                ('card_number', models.CharField(blank=True, max_length=16)),
                ('card_holder', models.CharField(max_length=100)),
                ('expiry_date', models.CharField(help_text='Format: MM/YY', max_length=5)),
                ('cvv', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'paiement par carte algérienne',
                'verbose_name_plural': 'paiements par carte algérienne',
            },
        ),
        migrations.CreateModel(
            name='EdahabiaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Numéro de téléphone Algérien (10 chiffres)', max_length=10)),
                ('transaction_code', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'paiement Edahabia',
                'verbose_name_plural': 'paiements Edahabia',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix (DZD)')),
                ('duration_days', models.PositiveIntegerField(verbose_name='durée (jours)')),
                ('plan_type', models.CharField(choices=[('monthly', 'Mensuel'), ('annual', 'Annuel'), ('lifetime', 'À vie')], max_length=10, verbose_name="type d'abonnement")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('features', models.JSONField(default=list, verbose_name='caractéristiques')),
            ],
            options={
                'verbose_name': "plan d'abonnement",
                'verbose_name_plural': "plans d'abonnement",
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant (DZD)')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Carte de Crédit'), ('edahabia', 'Edahabia'), ('cib', 'CIB'), ('paypal', 'PayPal'), ('bank_transfer', 'Virement Bancaire')], default='credit_card', max_length=20, verbose_name='méthode de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=10, verbose_name='statut')),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True, verbose_name='numéro de transaction')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='date de paiement')),
                ('receipt_url', models.URLField(blank=True, verbose_name='lien de reçu')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='courses.course', verbose_name='cours')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-payment_date'],
            },
        ),
    ]
