# Generated by Django 5.2 on 2025-05-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_companyprofile_isfreelancer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='isfreelancer',
            new_name='is_freelancer',
        ),
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='isfreelancer',
            new_name='is_freelancer',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='isfreelancer',
        ),
        migrations.AddField(
            model_name='user',
            name='is_freelancer',
            field=models.BooleanField(default=False),
        ),
    ]
