# Generated by Django 5.2 on 2025-05-23 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verification_token_expires',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
    ]
