# Generated by Django 5.2 on 2025-05-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='company_pics/'),
        ),
    ]
