# Generated by Django 5.2 on 2025-05-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_companyprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='country',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
