# Generated by Django 5.2 on 2025-05-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_companyprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='country',
            field=models.CharField(max_length=10),
        ),
    ]
