# Generated by Django 5.2 on 2025-05-29 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_companyprofile_wilaya_studentprofile_wilaya_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='wilaya',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='wilaya',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='wilaya',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
