# Generated by Django 4.2.19 on 2025-05-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('company_name', models.CharField(max_length=255)),
                ('company_industry', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Algeria', max_length=100)),
                ('work_mode', models.CharField(choices=[('REMOTE', 'Remote'), ('ONSITE', 'On-site'), ('HYBRID', 'Hybrid')], default='ONSITE', max_length=10)),
                ('remote_option', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('design', 'Graphic Design'), ('data', 'Data Entry'), ('writing', 'Content Writing'), ('marketing', 'Marketing'), ('other', 'Other')], default='other', max_length=50)),
                ('sector', models.CharField(choices=[('it', 'IT'), ('telecoms', 'Telecoms'), ('internet', 'Internet'), ('finance', 'Finance'), ('other', 'Other')], default='other', max_length=100)),
                ('experience_level', models.CharField(choices=[('junior', 'Junior'), ('confirmed', 'Confirmed'), ('expert', 'Expert')], default='junior', max_length=50)),
                ('contract_type', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='cdi', max_length=50)),
                ('education_level', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('other', 'Other')], default='other', max_length=50)),
                ('number_of_positions', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('applications_count', models.IntegerField(default=0)),
                ('accepted_applications', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('draft', 'Draft')], default='open', max_length=10)),
                ('main_missions', models.TextField()),
                ('commercial_support', models.TextField()),
                ('development_tasks', models.TextField()),
                ('requirements', models.TextField()),
                ('additional_responsibilities', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_contact', models.CharField(choices=[('email', 'البريد الإلكتروني'), ('phone', 'الهاتف'), ('both', 'الاثنين')], default='email', max_length=10)),
                ('certificates', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('cover_letter', models.TextField()),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('status', models.CharField(choices=[('pending', 'في انتظار'), ('reviewed', 'تم المراجعة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
