# Generated by Django 5.2 on 2025-05-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='preferred_contact',
            field=models.CharField(choices=[('email', 'email'), ('phone', 'phone'), ('both', 'both')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('reviewed', 'reviewed'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
    ]
