# Generated by Django 5.2 on 2025-05-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('design', 'Graphic Design'), ('data', 'Data Entry'), ('writing', 'Content Writing'), ('marketing', 'Marketing'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('draft', 'Draft')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='proposal',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
