# Generated by Django 5.2.1 on 2025-05-31 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contract_type', models.CharField(max_length=50)),
                ('expiration_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('required_skills', models.CharField(max_length=255)),
                ('industry_sector', models.CharField(max_length=255)),
                ('education_level', models.CharField(max_length=255)),
                ('job_level', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('introduction', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='job_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
