# Generated by Django 4.2.19 on 2025-05-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Company logo image', null=True, upload_to='company_logos/'),
        ),
    ]
