# Generated by Django 5.2 on 2025-05-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_location_job_work_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='work_mode',
        ),
    ]
