# Generated by Django 5.2 on 2025-05-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_job_location_remove_job_work_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='work_mode',
            field=models.CharField(choices=[('REMOTE', 'Remote'), ('ONSITE', 'On-site'), ('HYBRID', 'Hybrid')], default='ONSITE', max_length=10),
        ),
    ]
