# Generated by Django 5.2 on 2025-05-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.ManyToManyField(related_name='courses', to='skills.skill'),
        ),
    ]
