# Generated by Django 5.2 on 2025-05-31 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending Review'), ('rejected', 'Rejected')], default='draft', max_length=10),
        ),
    ]
