# Generated by Django 5.2 on 2025-05-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatyoulearn',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
