# Generated by Django 5.2 on 2025-05-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_whatyoulearn_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatyoulearn',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
