# Generated by Django 5.2 on 2025-05-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_whatyoulearn_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatyoulearn',
            old_name='text',
            new_name='notes',
        ),
    ]
