# Generated by Django 5.2 on 2025-05-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_text_whatyoulearn_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatyoulearn',
            options={'verbose_name': 'Learning Objective', 'verbose_name_plural': 'Learning Objectives'},
        ),
        migrations.RemoveField(
            model_name='whatyoulearn',
            name='notes',
        ),
        migrations.AddField(
            model_name='whatyoulearn',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
