# Generated by Django 5.2 on 2025-05-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_whatyoulearn_options_remove_whatyoulearn_notes_and_more'),
    ]

    operations = [
    ]
