# Generated by Django 5.2 on 2025-05-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20250522_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatyoulearn',
            options={},
        ),
    ]
