# Generated by Django 5.2 on 2025-05-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_whatyoulearn_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatyoulearn',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
