# Generated by Django 5.2 on 2025-05-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatyoulearn',
            name='description',
            field=models.TextField(),
        ),
    ]
