# Generated by Django 5.2 on 2025-05-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_category_options_remove_whatyoulearn_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatyoulearn',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
