# Generated by Django 5.2 on 2025-05-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_whatyoulearn_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatyoulearn',
            name='description',
            field=models.TextField(),
        ),
    ]
