# Generated by Django 5.2 on 2025-05-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_enrollment_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('all levels', 'All Levels')], default='Beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10),
        ),
    ]
