# Generated by Django 4.2.19 on 2025-05-26 05:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected'), ('ban_user', 'User Banned'), ('delete_content', 'Content Deleted'), ('warn_user', 'User Warned')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_object', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Journal de modération',
                'verbose_name_plural': 'Journaux de modération',
                'ordering': ['-timestamp'],
            },
        ),
    ]
