<<<<<<< HEAD
# Generated by Django 4.2.20 on 2025-05-23 19:17

from django.db import migrations, models
import django.utils.timezone
=======
# Generated by Django 5.2 on 2025-05-23 09:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
>>>>>>> origin/Back2_dynamic_homepage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> origin/Back2_dynamic_homepage
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected'), ('ban_user', 'User Banned'), ('delete_content', 'Content Deleted'), ('warn_user', 'User Warned')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_object', models.CharField(blank=True, max_length=255)),
<<<<<<< HEAD
=======
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_logs', to=settings.AUTH_USER_MODEL)),
>>>>>>> origin/Back2_dynamic_homepage
            ],
            options={
                'verbose_name': 'Journal de modération',
                'verbose_name_plural': 'Journaux de modération',
                'ordering': ['-timestamp'],
            },
        ),
    ]
