# Generated by Django 5.2.1 on 2025-05-22 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('course', 'Course'), ('job', 'Job'), ('profile', 'Profile')], max_length=20)),
                ('content_id', models.IntegerField()),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
