# Generated by Django 5.2.1 on 2025-05-23 00:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderationlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Journal de modération', 'verbose_name_plural': 'Journaux de modération'},
        ),
        migrations.RemoveField(
            model_name='moderationlog',
            name='action_date',
        ),
        migrations.RemoveField(
            model_name='moderationlog',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='moderationlog',
            name='content_id',
        ),
        migrations.RemoveField(
            model_name='moderationlog',
            name='content_type',
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='related_object',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='target_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='action',
            field=models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected'), ('ban_user', 'User Banned'), ('delete_content', 'Content Deleted'), ('warn_user', 'User Warned')], max_length=20),
        ),
    ]
