# Generated by Django 4.2.19 on 2025-05-26 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_proficiencies', to='users.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('student_profile', 'skill')},
        ),
    ]
