# Generated by Django 5.2 on 2025-05-12 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_proficiencies', to='users.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('student_profile', 'skill')},
        ),
    ]
