# Generated by Django 5.2.1 on 2025-05-30 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_proficiencies', to='users.profile'),
        ),
        migrations.AddField(
            model_name='userskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_proficiencies', to='skills.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('profile', 'skill')},
        ),
    ]
